// Copies compiled ABIs into @nestledger/shared (SPEC §5.10 step 12).
// Implementation ABIs win over interface ABIs once the contracts exist.
import fs from "fs";
import path from "path";

const CONTRACTS = [
  "NestRegistry", "NestPassport", "AttestedEscrow", "RentalEscrow",
  "MilestoneEscrow", "DisputeResolver", "SocietyLedger", "TankerTrust",
];
const ARTIFACTS = path.join(__dirname, "..", "artifacts", "contracts");
const OUT = path.join(__dirname, "..", "..", "shared", "src", "abis");

function findArtifact(name: string): { abi: unknown[] } | null {
  const candidates = [
    path.join(ARTIFACTS, `${name}.sol`, `${name}.json`),
    path.join(ARTIFACTS, "core", `${name}.sol`, `${name}.json`),
    path.join(ARTIFACTS, "interfaces", `I${name}.sol`, `I${name}.json`),
  ];
  const file = candidates.find((f) => fs.existsSync(f));
  return file ? JSON.parse(fs.readFileSync(file, "utf8")) : null;
}

const lowerFirst = (s: string) => s[0].toLowerCase() + s.slice(1);
fs.mkdirSync(OUT, { recursive: true });
let index = "// Auto-generated by packages/contracts/scripts/export-abis.ts. Do not edit.\n\n";
for (const name of CONTRACTS) {
  const artifact = findArtifact(name);
  if (!artifact) throw new Error(`No artifact for ${name}; run hardhat compile first`);
  fs.writeFileSync(path.join(OUT, `${name}.json`), JSON.stringify(artifact.abi, null, 2) + "\n");
  index += `export const ${lowerFirst(name)}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
  console.log(`  ${name}: ${artifact.abi.length} entries`);
}
fs.writeFileSync(path.join(OUT, "index.ts"), index);
console.log(`ABIs written to ${OUT}`);
